#!/usr/bin/env node

'use strict';

const commander = require('commander');
const { CLIEngine } = require('eslint');
const explain = require('./explain');

commander
  .version('0.0.1')
  .command('eslint-explainer filename', 'output the explained list of eslint rules applied to that file')
  .action((file) => {
    const config = new CLIEngine({}).getConfigForFile(file);
    console.log(explain(config.rules));
  })
  .parse(process.argv);
