#!/usr/bin/env node
'use strict';

const explain = require('./explain');
const path = require('path');

const filename = process.argv[2] || '.';

// load project eslint
const eslintPath = path.join(process.cwd(), '/node_modules/eslint')
const { CLIEngine } = require(eslintPath);

const config = new CLIEngine({}).getConfigForFile(filename);
const explainedRules = explain({
  rules: config.rules,
  colors: true
});

console.log(explainedRules);